In [2]:
import os
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv("./bases/complete_db.csv")

In [4]:
df = df[df["status"] == "Released"]

In [5]:
df.columns

Index(['Unnamed: 0', 'id', 'value_x', 'Title', 'Year', 'Rated', 'Released',
       'Runtime', 'Genre', 'Director', 'Writer', 'Actors', 'Plot', 'Language',
       'Country', 'Awards', 'Poster', 'Ratings', 'Metascore', 'imdbRating',
       'imdbVotes', 'imdbID', 'Type', 'DVD', 'BoxOffice', 'Production',
       'Website', 'Response', 'Season', 'Episode', 'seriesID', 'Error', 'id_x',
       'imdb_id', 'value_y', 'adult', 'backdrop_path', 'belongs_to_collection',
       'budget', 'genres', 'homepage', 'id_y', 'origin_country',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count',
       'belongs_to_collection.id', 'belongs_to_collection.name',
       'belongs_to_collection.poster_path',
       'belongs_to_collection.backdrop_path'],
      dtype='object')

In [6]:
#columns_to_ignore = [
#    "Poster", "Awards", "Season","video","DVD",
#    "homepage","poster_path","tagline","Website","Plot","Episode","Season","overview",   
#]

columns_to_use = {
    "id", "Title", "Year", "Ratings", "runtime", "Genre", 
    "Ratings", "budget", 'revenue', 'popularity', "production_companies", "BoxOffice",
}

columns_to_drop = set(df.columns) - columns_to_use

df = df.drop(columns_to_drop, axis=1)

In [7]:
import ast

# Function to convert list of dicts into a dict
def extract_ratings(ratings_list):
    return {item['Source']: item['Value'] for item in ratings_list}

#df['Ratings'].apply(json.loads).apply(extract_ratings).apply(pd.Series)

df = pd.concat([
    df.drop(columns=["Ratings"]),
    df['Ratings'].apply(json.loads).apply(extract_ratings).apply(pd.Series)
], axis=1)

In [8]:
def extract_companies(companies_list):
    names = [item['name'] for item in companies_list]
    return ','.join(names)

df["production_companies"] = df["production_companies"].apply(json.loads).apply(extract_companies)

In [ ]:
df = df[(df['budget'] > 0) & (df['revenue'] > 0)]
df = df[]
# print(df['ratings'].value_counts())

,id,Title,Year,Genre,BoxOffice,budget,popularity,production_companies,revenue,runtime,Internet Movie Database,Rotten Tomatoes,Metacritic
11,tt14827150,The Last Breath,2024,"Horror, Thriller","$3,214",30000,4.5953,"Anamorphic Films,Filmgate Films,Picaro Films,F...",273650,96,4.7/10,30%,NaN
13,tt20315818,Ezra,2023,"Comedy, Drama","$2,631,460",5000000,6.5663,"Closer Media,Wayfarer Studios",3046741,100,6.5/10,70%,NaN
18,tt11908172,The Kill Room,2023,"Comedy, Thriller","$139,358",50000000,6.5394,"Yale Productions,Idiot Savant Pictures,Untitle...",476375,98,5.5/10,59%,58/100
20,tt11687104,"Alice, Darling",2022,"Drama, Mystery, Romance","$101,000",4000000,4.2332,"Babe Nation Films,Elevation Pictures,Lionsgate",121067,90,5.6/10,84%,65/100
25,tt1798632,Firestarter,2022,"Drama, Horror, Sci-Fi","$9,739,250",12000000,6.9572,"Blumhouse Productions,Weed Road Pictures,Bould...",15000000,94,4.6/10,10%,32/100

In [ ]:
df.to_csv("bruno_db.csv", index=False)

,id,Title,Year,Genre,BoxOffice,budget,popularity,production_companies,revenue,runtime,Internet Movie Database,Rotten Tomatoes,Metacritic
0,tt20114686,Femme,2023,"Drama, Thriller","$187,053",0,2.8926,Agile Films,0,99,7.3/10,93%,69/100
1,tt30467885,Goebbels and the Führer,2024,"Biography, Drama, History",NaN,0,2.1574,"Zeitsprung Pictures,SWR,act headquarter media",547033,123,6.7/10,NaN,NaN
2,tt28223926,Skincare,2024,"Comedy, Horror, Mystery","$456,590",0,5.4150,"Jalapeno Goat,Iervolino & Lady Bacardi Enterta...",451381,96,5.7/10,69%,NaN
3,tt6318608,Nightwatch: Demons Are Forever,2023,"Horror, Mystery, Thriller",NaN,4300000,33.0393,Nordisk Film Denmark,0,117,5.8/10,69%,50/100
4,tt6432466,Moxie,2021,"Comedy, Drama",NaN,0,3.1624,Paper Kite Productions,0,111,6.7/10,70%,54/100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3945,tt32064571,Nova & Alice,2024,"Drama, Music",NaN,0,1.3766,"Film i Väst,Nordisk Film Sweden,StellaNova Film",0,99,6.5/10,NaN,NaN
3946,tt15600222,An Action Hero,2022,"Action, Comedy, Crime",NaN,0,1.1909,"T-Series,Colour Yellow Productions,Cars on Film",0,128,7.0/10,85%,NaN
3947,tt8290476,Blank,2022,"Drama, Sci-Fi, Thriller",NaN,275650,1.2619,Templeheart Films,0,95,4.7/10,88%,NaN
3948,tt26731970,All the Long Nights,2024,Drama,NaN,0,2.3107,"Asmik Ace,Bandai Namco Filmworks,THEFOOL",0,119,7.2/10,NaN,NaN
3949,tt18950300,Shoulder Dance,2023,"Comedy, Drama, Romance",NaN,0,1.0420,Shoulder Dance,0,103,5.7/10,NaN,NaN